apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.opensearch_service.opensearch_service_name }}
  name: {{ .Values.opensearch_service.opensearch_service_name }}
spec:
  ports:
  - name: "5601"
    port: {{ .Values.opensearch_service.opensearch_service_port }}
    targetPort: 5601
  selector:
    service: {{ .Values.opensearch_service.opensearch_service_name }}
  type: {{ .Values.opensearch_service.opensearch_service_type }}
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.opensearch_service_node.opensearch_service_node_name }}
  name: {{ .Values.opensearch_service_node.opensearch_service_node_name }}
spec:
  ports:
  - name: "9200"
    port: {{ .Values.opensearch_service_node.opensearch_service_node_port1 }}
    targetPort: 9200
  - name: "9600"
    port: {{ .Values.opensearch_service_node.opensearch_service_node_port2 }}
    targetPort: 9600
  selector:
    service: {{ .Values.opensearch_service_node.opensearch_service_node_name }}
status:
  loadBalancer: {}
